rm -f units/*.o
rm -f units/*.obj
rm -f units/*.or
rm -f units/*.ppu
rm -f units/*.res
rm -f units/*.rsj
rm -f options/units/*.o
rm -f options/units/*.obj
rm -f options/units/*.or
rm -f options/units/*.ppu
rm -f options/units/*.res
rm -f options/units/*.rsj
rm -f ../config/*.ini
rm -f ../config/*.log
rm -f ../config/eschecs.fen
rm -f ../game.pgn
